### ISSUE TITLE
User must log out and back in after payment for it to take effect.

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#31]
Just a little hinky...

**Comment by JT-Bruch** [comment]
I thought so too.. I dicked around with that for about an hour and couldn't figure out a good way to reset all the information because I have to generation a new authorization token with new credentials associated with it which requires re-entering the username and password.

What do you think about automatically logging them out upon success and then taking them back to the login screen?

**Comment by tbruch** [comment]
That would work well, especially if you give them a message thanking for
the payment and asking them to login.

Thanks!

Tom Bruch
Exceleration Designs, Inc.
http://BigSkyInternetDesign.com

979-776-5160

**Comment by JT-Bruch** [comment]
Made it do that Works pretty now
